export const WS_EVENTS = {
  // Client -> Server
  AUTH_TOKEN: 'auth:token',
  ROOM_CREATE: 'room:create',
  ROOM_JOIN: 'room:join',
  QUEUE_JOIN: 'queue:join',
  QUEUE_LEAVE: 'queue:leave',
  MOVE_SUBMIT: 'move:submit',
  DRAW_OFFER: 'draw:offer',
  DRAW_RESPOND: 'draw:respond',
  GAME_RESIGN: 'game:resign',
  GAME_REMATCH: 'game:rematch',
  REMATCH_RESPOND: 'game:rematch:respond',
  REMATCH_CANCEL: 'game:rematch:cancel',

  // Server -> Client
  GAME_INIT: 'game:init',
  MOVE_ACCEPTED: 'move:accepted',
  MOVE_REJECTED: 'move:rejected',
  CLOCK_TICK: 'clock:tick',
  GAME_ENDED: 'game:ended',
  DRAW_OFFERED: 'draw:offered',
  PLAYER_PRESENCE: 'player:presence',
  QUEUE_STATUS: 'queue:status',
  QUEUE_MATCHED: 'queue:matched',
  ERROR: 'error',
  REMATCH_OFFERED: 'rematch:offered',
  REMATCH_DECLINED: 'rematch:declined',
  REMATCH_CANCELLED: 'rematch:cancelled',

  // Phase 6C Social, Presence & Challenge Events
  PRESENCE_UPDATED: 'presence:updated',
  FRIEND_REQUEST_RECEIVED: 'friend:request_received',
  FRIEND_REQUEST_ACCEPTED: 'friend:request_accepted',
  CHALLENGE_RECEIVED: 'challenge:received',
  CHALLENGE_ACCEPTED: 'challenge:accepted',
  CHALLENGE_DECLINED: 'challenge:declined',
  CHALLENGE_EXPIRED: 'challenge:expired',
  CHALLENGE_CANCELLED: 'challenge:cancelled',

  // Phase 8 Tournament Events
  TOURNAMENT_JOIN: 'tournament:join',
  TOURNAMENT_LEAVE: 'tournament:leave',
  TOURNAMENT_UPDATED: 'tournament:updated',
  TOURNAMENT_STARTED: 'tournament:started',
  TOURNAMENT_ROUND_STARTED: 'tournament:round_started',
  TOURNAMENT_PAIRING_CREATED: 'tournament:pairing_created',
  TOURNAMENT_GAME_STARTED: 'tournament:game_started',
  TOURNAMENT_STANDINGS_UPDATED: 'tournament:standings_updated',
  TOURNAMENT_ROUND_COMPLETED: 'tournament:round_completed',
  TOURNAMENT_FINISHED: 'tournament:finished',
  TOURNAMENT_CANCELLED: 'tournament:cancelled'
};

export const ERROR_CODES = {
  NOT_YOUR_TURN: 'NOT_YOUR_TURN',
  INVALID_MOVE: 'INVALID_MOVE',
  GAME_NOT_FOUND: 'GAME_NOT_FOUND',
  GAME_FINISHED: 'GAME_FINISHED',
  ROOM_FULL: 'ROOM_FULL',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  EXPIRED_TIME: 'EXPIRED_TIME',
  ALREADY_IN_QUEUE: 'ALREADY_IN_QUEUE',
  ALREADY_IN_MATCHMAKING_QUEUE: 'ALREADY_IN_MATCHMAKING_QUEUE',
  PLAYER_ALREADY_IN_GAME: 'PLAYER_ALREADY_IN_GAME',
  INVALID_RATING_TYPE: 'INVALID_RATING_TYPE',
  TOURNAMENT_NOT_FOUND: 'TOURNAMENT_NOT_FOUND',
  TOURNAMENT_FINISHED: 'TOURNAMENT_FINISHED',
  TOURNAMENT_FULL: 'TOURNAMENT_FULL',
  ALREADY_REGISTERED: 'ALREADY_REGISTERED',
  NOT_IN_QUEUE: 'NOT_IN_QUEUE',
  STALE_STATE: 'STALE_STATE',

  // Phase 6C Social, Challenge & RBAC Error Codes
  CANNOT_FRIEND_SELF: 'CANNOT_FRIEND_SELF',
  ALREADY_FRIENDS: 'ALREADY_FRIENDS',
  FRIEND_REQUEST_PENDING: 'FRIEND_REQUEST_PENDING',
  FRIEND_REQUEST_NOT_FOUND: 'FRIEND_REQUEST_NOT_FOUND',
  USER_BLOCKED: 'USER_BLOCKED',
  CANNOT_BLOCK_SELF: 'CANNOT_BLOCK_SELF',
  CANNOT_CHALLENGE_SELF: 'CANNOT_CHALLENGE_SELF',
  CHALLENGE_NOT_FOUND: 'CHALLENGE_NOT_FOUND',
  CHALLENGE_EXPIRED: 'CHALLENGE_EXPIRED',
  CHALLENGE_ALREADY_RESOLVED: 'CHALLENGE_ALREADY_RESOLVED',

  // Phase 8 Tournament Error Codes
  NOT_REGISTERED: 'NOT_REGISTERED',
  TOURNAMENT_ALREADY_STARTED: 'TOURNAMENT_ALREADY_STARTED',
  TOURNAMENT_NOT_RUNNING: 'TOURNAMENT_NOT_RUNNING',
  INVALID_TOURNAMENT_STATE: 'INVALID_TOURNAMENT_STATE',
  INSUFFICIENT_PLAYERS: 'INSUFFICIENT_PLAYERS',
  ROUND_IN_PROGRESS: 'ROUND_IN_PROGRESS',
  PAIRING_ERROR: 'PAIRING_ERROR',

  // Phase 7 Rematch Error Codes
  GAME_NOT_FINISHED: 'GAME_NOT_FINISHED',
  TOURNAMENT_REMATCH_NOT_ALLOWED: 'TOURNAMENT_REMATCH_NOT_ALLOWED',
  REMATCH_ALREADY_PENDING: 'REMATCH_ALREADY_PENDING',
  REMATCH_ALREADY_RESOLVED: 'REMATCH_ALREADY_RESOLVED',
  REMATCH_NOT_FOUND: 'REMATCH_NOT_FOUND',
  REMATCH_EXPIRED: 'REMATCH_EXPIRED'
};
